<!--NAVIGATION-->
<a href="https://colab.research.google.com/github/marcoteran/artificialintelligence/blob/master/notebooks/00_introtopython/04_artificialintelligence_numpyhomework.ipynb" target="_blank"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Abrir en Colab" title="Abrir y ejecutar en Google Colaboratory"></a>

### Taller
# Taller: Introducción a NumPy
## Inteligencia Artificial

**Name:** Marco Teran ***E-mail:*** marco.tulio.teran@gmail.com [Website](http://marcoteran.github.io/),
[Github](https://github.com/marcoteran),
[LinkedIn](https://www.linkedin.com/in/marcoteran/).
___

Escriba su nombre completo
### Nombre: 
Jhon Alexander Sabogal Lopez

## Ejercicios

Conteste las preguntas o complete las tareas que se presentan en negrilla a continuación. Use los métodos de Python cuando sea necesario.

#### Importar NumPy como np

In [32]:
import numpy as np

#### Crear un arreglo de 10 ceros 

In [83]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Crear un arreglo de 10 unos

In [82]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Crear un arreglo de 10 cincos

In [81]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Crear un arreglo de los números enteros desde 10 hasta 50 (incluido)

In [80]:
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Crear un arreglo de todos los números pares entre 10 y 50 (incluido)

In [79]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Crear una matriz de 3x3 con valores desde 0 a 8

In [78]:
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Crear una matriz identidad de 3x3

In [75]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Usar NumPy para generar un número aleatorio entre 0 y 1

In [74]:
np.random.rand()

0.9330478187533221

#### Usar NumPy para generar 25 números aleatorios con una distribución de probabilidad normal

In [73]:
np.random.standard_normal(25)

array([ 2.07452393,  0.55499191,  0.58719703,  0.09491909,  0.55883913,
       -0.10825258, -0.81773885,  0.22534103, -0.60652605, -0.1329708 ,
       -0.01103947, -0.75323324,  0.88415621,  0.33949217,  0.10180826,
        0.49643263, -1.89239607,  0.02837826, -0.86999458,  0.50248342,
       -2.79470896,  0.69473289, -0.0915445 ,  1.57257494,  0.61325687])

#### Crear la siguiente matriz:

In [72]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Crear un arreglo de 20 elementos linealmente separados entre 0 y 1:

In [52]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy - Índices y Selección

A partir de la siguiente matriz, replique los resultados que se presentan a continuación:

In [33]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
a=np.delete(mat, 0, axis=1)
np.delete(a, (0,1), axis=0)

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [43]:
mat[3][4]

20

20

In [70]:
mat[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [49]:
np.delete(mat, (0,1,2,3), axis=0)

array([[21, 22, 23, 24, 25]])

array([21, 22, 23, 24, 25])

In [50]:
np.delete(mat, (0,1,2), axis=0)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## NumPy - Operaciones

#### Obtener la suma de todos los valores de la matriz 'mat'

In [41]:
mat.sum()

325

#### Obtener las desviación estándar de los valores en la matriz 'mat'

In [40]:
mat.std()

7.211102550927978

#### Obtener la suma de los valores en cada columna de la matriz

In [42]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])